DEFAULT_SYMBOL = 'BTCUSD'
DEFAULT_TIMEFRAME_LABEL = '1h'
DEFAULT_INDICATOR_LABEL = 'None'

SYMBOL_OPTIONS = (
	'EURUSD', 'USDJPY', 'GBPUSD', 'USDCHF', 'AUDUSD', 'USDCAD', 'NZDUSD',
	'EURGBP', 'EURCHF', 'EURJPY', 'GBPJPY', 'CHFJPY', 'AUDJPY', 'CADJPY',
	'NZDJPY', 'AUDNZD', 'AUDCHF', 'GBPCHF', 'CADCHF', 'BTCUSD', 'ETHUSD',
	'XRPUSD', 'BNBUSD', 'ADAUSD', 'SOLUSD', 'LTCUSD', 'DOTUSD', 'XTIUSD',
	'XAUUSD'
)

PAGE_SIZE = 1000
EXTEND_SIZE = 1000
LOAD_MORE_THRESHOLD = 200

MT5_HOST = '0.0.0.0'
MT5_PORT = 8001
